function vehicle = quarter_car_parameters()
%QUARTER_CAR_PARAMETERS Front/rear SN5 quarter-car parameters.
%   Motion ratio is defined as damper travel divided by wheel travel.
%   Spring rates are physical coil rates; wheel rate is k_coil*MR^2.

vehicle.tire_rate = 114182.804; % N/m, implied by highlighted ride-rate sheet
vehicle.gravity = 9.81;         % m/s^2

vehicle.front = make_corner( ...
    "Front", ...
    71.2788879633, ... % sprung mass per corner, kg
    11.18, ...         % unsprung mass per corner, kg
    52537.8, ...       % 300 lb/in physical coil rate, N/m
    0.782, ...         % damper travel / wheel travel
    vehicle.tire_rate, vehicle.gravity);

vehicle.rear = make_corner( ...
    "Rear", ...
    65.4220298085, ... % sprung mass per corner, kg
    10.38, ...         % unsprung mass per corner, kg
    35025.2, ...       % 200 lb/in physical coil rate, N/m
    0.746, ...         % damper travel / wheel travel
    vehicle.tire_rate, vehicle.gravity);
end

function corner = make_corner(name, sprung_mass, unsprung_mass, ...
    coil_rate, motion_ratio, tire_rate, gravity)

corner = struct( ...
    'name', name, ...
    'sprung_mass', sprung_mass, ...
    'unsprung_mass', unsprung_mass, ...
    'coil_rate', coil_rate, ...
    'motion_ratio', motion_ratio, ...
    'wheel_rate', coil_rate*motion_ratio^2, ...
    'tire_rate', tire_rate, ...
    'gravity', gravity, ...
    'static_tire_load', (sprung_mass + unsprung_mass)*gravity);
end
